# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitDepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='Rehber Deposu ', max_length=50)),
                ('adres', models.URLField(verbose_name='Git Depo Adresi')),
            ],
            options={
                'verbose_name': 'Git Depo Ayarı',
                'db_table': 'RehberDepo',
                'verbose_name_plural': 'Git Depo Ayarları',
            },
        ),
    ]
