# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komutaModul', '0003_betikler_gitdepo_parametreler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitdepo',
            old_name='depoAdresi',
            new_name='adres',
        ),
        migrations.AddField(
            model_name='gitdepo',
            name='isim',
            field=models.CharField(default='Depo', max_length=50, verbose_name='Betiğin aldığı parametre'),
        ),
    ]
