# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cekirdek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglanti',
            name='kullanici',
            field=models.CharField(help_text='Buraya Komutan kullanıcı adınızı değil sistem kullanıcı adınızı giriniz. ', max_length=32, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='sifre',
            field=models.CharField(max_length=40, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='sunucu',
            field=models.CharField(default='localhost', max_length=50, verbose_name='SSH Sunucu Adresi'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='arkaplan',
            field=models.FilePathField(default='mavi.png', match='.*\\.png$', path='/opt/komutan2/static/img/artalanlar', recursive=True, verbose_name='Arayüz arkaplan resmi'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='koyuYazı',
            field=models.BooleanField(verbose_name='Koyu renk yazı kullanılsın'),
        ),
    ]
