# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cekirdek', '0002_auto_20170624_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='arkaplan',
            field=models.FilePathField(default='mavi.png', match='.*\\.png$', path='/root/komutan-next/static/img/artalanlar', recursive=True, verbose_name='Arayüz arkaplan resmi'),
        ),
    ]
